spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD:12345}
    url: jdbc:mysql://${DB_HOST:localhost}:3306/mobilele
    username: ${DB_USERNAME:root}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always

api:
  security-secret-key: "topSecretBra"
  base-url: "/car/api"

