version: '3.8'

services:
  mysql:
    container_name: my-mysql-container
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mobilele
    volumes:
      - /mysql-data:/var/lib/mysql
