version: '3.8'

services:
  mysql-db:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: mobilele
    volumes:
      - mysql-data-mobilele:/var/lib/mysql
    networks:
      - spring-app-mobilele
volumes:
  mysql-data-mobilele:
networks:
  spring-app-mobilele: