name: Gradle Build and Test

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  gradle:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: 'gradle'
        distribution: corretto
    - name : buld
      run: |
        cd server
        cd mobilele
        ./gradlew build --no-daemon

