name: Gradle Build and Test

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  gradle:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        path: server/mobilele
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: 'gradle'
        distribution: corretto

    - name : build
      run: ./gradlew build --no-daemon

