name: Gradle Build and Test

on:
  push:
    branches:
      - main # Adjust this to match the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Adjust the Java version to your project's requirements

    - name: Build and Test with Gradle
      run: |
        cd server
        cd mobilele
        ./gradlew build 
        ./gradlew test  

