name: Gradle Build and Test

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  mobilele_CI:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: 'gradle'
        distribution: corretto

    - name : test
      working-directory: ./server/mobilele
      run: ./gradlew test --no-daemon
      
    - name : build
      working-directory: ./server/mobilele
      run: ./gradlew build --no-daemon
      
  mobilele_CD:
    runs-on: windows-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          dockerfile: DockerFileServer
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mobilele:latest
    
    
    

