name: Gradle Build and Test

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        path: server/mobilele
        
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        gradle-version: 7.x
      
    - name: Execute Gradle build
      run: ./gradlew build

