name: Gradle Build and Test

on:
  push:
    branches:
      - main # Adjust this to match the name of your main branch

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: |
        cd server
        cd mobilele
        ./gradlew build

