name: Gradle Build and Test

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  mobilele_CICD:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: 'gradle'
        distribution: corretto

    - name : test
      working-directory: ./server/mobilele
      run: ./gradlew test --no-daemon
      
    - name : build
      working-directory: ./server/mobilele
      run: ./gradlew build --no-daemon
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        dockerfile: DockerfileServer 
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/mobilele:latest
    
    

